services:
  redis:
    ports:
      - "6379:6379"

  backend:
    env_file:
      - .env
    volumes:
      - ./research:/workspace/research:ro
      - ./backend/storage:/app/storage
    ports:
      - "8000:8000"
    networks:
      internal: null
    environment:
      MODE: local
      
    labels:
      traefik.enable: "false"
      traefik.http.routers.backend.entrypoints: null
      traefik.http.routers.backend.rule: null
      traefik.http.services.backend.loadbalancer.server.port: null

  arq-worker:
    env_file:
      - .env
    volumes:
      - ./research:/workspace/research:ro
      - ./backend/storage:/app/storage

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=http://localhost:8000
        - VITE_WS_BASE_URL=ws://localhost:8000
        - NODE_ENV=development
    ports:
      - "5173:80"
    networks:
      internal: null
    labels:
      traefik.enable: "false"
      traefik.http.routers.frontend.entrypoints: null
      traefik.http.routers.frontend.rule: null
      traefik.http.services.frontend.loadbalancer.server.port: null

networks:
  internal:
  traefik-public:
    external: false
