// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ListJobStatusesApiJobsGetData, ListJobStatusesApiJobsGetResponse, SubmitJobApiJobsPostData, SubmitJobApiJobsPostResponse, JobStatusApiJobsJobIdGetData, JobStatusApiJobsJobIdGetResponse, JobResultApiJobsJobIdResultGetData, JobResultApiJobsJobIdResultGetResponse, DownloadArtifactsApiJobsJobIdDownloadGetData, DownloadArtifactsApiJobsJobIdDownloadGetResponse } from './types.gen';

export class DefaultService {
    /**
     * List Job Statuses
     * @param data The data for the request.
     * @param data.status
     * @param data.limit
     * @returns JobStatusResponse Successful Response
     * @throws ApiError
     */
    public static listJobStatusesApiJobsGet(data: ListJobStatusesApiJobsGetData = {}): CancelablePromise<ListJobStatusesApiJobsGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/jobs',
            query: {
                status: data.status,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Submit Job
     * @param data The data for the request.
     * @param data.formData
     * @returns JobCreatedResponse Successful Response
     * @throws ApiError
     */
    public static submitJobApiJobsPost(data: SubmitJobApiJobsPostData): CancelablePromise<SubmitJobApiJobsPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/jobs',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Job Status
     * @param data The data for the request.
     * @param data.jobId
     * @returns JobStatusResponse Successful Response
     * @throws ApiError
     */
    public static jobStatusApiJobsJobIdGet(data: JobStatusApiJobsJobIdGetData): CancelablePromise<JobStatusApiJobsJobIdGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/jobs/{job_id}',
            path: {
                job_id: data.jobId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Job Result
     * @param data The data for the request.
     * @param data.jobId
     * @returns JobResultResponse Successful Response
     * @throws ApiError
     */
    public static jobResultApiJobsJobIdResultGet(data: JobResultApiJobsJobIdResultGetData): CancelablePromise<JobResultApiJobsJobIdResultGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/jobs/{job_id}/result',
            path: {
                job_id: data.jobId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Download Artifacts
     * @param data The data for the request.
     * @param data.jobId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static downloadArtifactsApiJobsJobIdDownloadGet(data: DownloadArtifactsApiJobsJobIdDownloadGetData): CancelablePromise<DownloadArtifactsApiJobsJobIdDownloadGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/jobs/{job_id}/download',
            path: {
                job_id: data.jobId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}