name: Deploy to Staging

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on:
      - self-hosted
      - staging
    env:
      MODE: staging
      BACKEND_DOMAIN: ${{ secrets.BACKEND_DOMAIN_STAGING }}
      FRONTEND_DOMAIN: ${{ secrets.FRONTEND_DOMAIN_STAGING }}
      STACK_NAME: ${{ secrets.STACK_NAME_STAGING }}
      REDIS_PORT: ${{ secrets.REDIS_PORT}}
      REDIS_DB: ${{ secrets.REDIS_DB}}
      DATALAB_API_KEY: ${{ secrets.DATALAB_API_KEY}}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY}}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - run: docker compose -f docker-compose.yml --project-name ${{ secrets.STACK_NAME_STAGING }} build
      - run: docker compose -f docker-compose.yml --project-name ${{ secrets.STACK_NAME_STAGING }} up -d